#!/usr/bin/env guile
!#

;;; compost
;;; Copyright (C) 2014 Andy Wingo <wingo@pobox.com>
;;; 
;;; Compost is free software: you can redistribute it and/or modify it
;;; under the terms of the GNU General Public License as published by
;;; the Free Software Foundation, either version 3 of the License, or
;;; (at your option) any later version.
;;; 
;;; Compost is distributed in the hope that it will be useful, but WITHOUT
;;; ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
;;; or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
;;; License for more details.
;;; 
;;; You should have received a copy of the GNU General Public License
;;; along with this program.  If not, see
;;; <http://www.gnu.org/licenses/>.

(use-modules (compost packed-struct)
             (compost syntax)
             (rnrs bytevectors))

(define-packed-struct particle
  (x float)
  (y float)
  (z float)
  (vx float)
  (vy float)
  (vz float))

(define/compost (update-particles-visitor (particles bytevector?)
                                          (dt real?)
                                          (start exact-integer?)
                                          (end exact-integer?))
  (let ((half-dt-squared (* 0.5 dt dt)))
    ((repack-visitor
      particles
      particle
      (lambda (n x y z vx vy vz)
        (let* ((distance-squared (+ (* x x) (* y y) (* z z)))
               (distance (sqrt distance-squared))
               (F (/ -200.0 distance-squared))
               (ax (* F (/ x distance)))
               (ay (* F (/ y distance)))
               (az (* F (/ z distance))))
          (values (+ x (* vx dt) (* ax half-dt-squared))
                  (+ y (* vy dt) (* ay half-dt-squared))
                  (+ z (* vz dt) (* az half-dt-squared))
                  (+ vx (* ax dt))
                  (+ vy (* ay dt))
                  (+ vz (* az dt))))))
     start end)))
